version: '3'
services:
    phoenix.test:
        build:
            context: deps/phoenix_sail/priv/phoenix_sail/runtime/1.11
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: phoenix-sail/app
        ports:
            - '${APP_PORT:-80}:4000'
        environment:
            WWWUSER: '${WWWUSER}'
            DB_HOST: mysql
            DB_DATABASE: example_dev
            PHOENIX_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            # - selenium
    # selenium:
    #     image: 'selenium/standalone-chrome'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - sail
    #     depends_on:
    #         - phoenix.test
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_DATABASE: 'example_dev'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
    # postgres:
    #     image: postgres:13
    #     ports:
    #         - '${DB_PORT:-5432}:5432'
    #     environment:
    #         POSTGRES_PASSWORD: ''
    #         POSTGRES_USER: 'root'
    #         POSTGRES_DB: 'example_dev'
    #         POSTGRES_HOST_AUTH_METHOD: trust
    #     volumes:
    #         - 'sailpostgres:/var/lib/postgresql/data'
    #     networks:
    #         - sail

    redis:
        image: 'redis:alpine'
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
    # memcached:
    #     image: 'memcached:alpine'
    #     ports:
    #         - '11211:11211'
    #     networks:
    #         - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    # sailpostgres:
    #     driver: local