#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.mix ]; then
    mix local.hex --force
fi

chmod -R ugo+rw /.mix

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    exec gosu $WWWUSER mix phx.server
fi
